image: python:alpine
stages:
  - lint
  - deploy

lint:
  stage: lint
  before_script:
    - apk add --no-cache make
    - pip3 install tox
  script:
    - make lint

deploy:
  stage: deploy
  before_script:
    - apk update && apk add openssh-client git
    - 'which ssh-agent || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config

  script:
    - ssh -o StrictHostKeyChecking=no $USER@$SERVER  'bash -s' < scripts/deploy.sh $CI_COMMIT_REF_NAME