version: '3'
services:
  app:
    container_name: record-flask-app-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    container_name: record-flask-app-mongo
    image: mongo:4.2
    ports:
      - 27017:27017